### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added

### ISSUE THREAD

**Issue by IgorSh90** [Krupen/FabulousFilter#20]
Hello! I get this exception, if i press FAB twice:
```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: FilterFragment{a78520b #7}
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1886)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2591)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2378)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2333)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2240)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6564)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

In the example project it's the same. What can i do about it?

**Comment by Krupen** [comment]
I am not able to reproduce this, can you try again with version 0.0.6?
